video: fbdev: Fix clang -Werror,-Wstrict-prototypes
Caused by:
../drivers/video/fbdev/msm/mdss_mdp.c:4651:32: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
struct irq_info *mdss_intr_line()
                               ^
                                void

../drivers/video/fbdev/msm/mdss_util.c:255:42: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
struct mdss_util_intf *mdss_get_util_intf()
                                         ^
                                          void

Signed-off-by: Aditya Eka Pranata <aepranata@gmail.com>